config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :rooms
  resources :categories
  devise_for :hotels
  resources :hotels
  resources :bookings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'home#index'
  resources :home, only: [:index] do
    collection do
      get :today_sales
      get :yesterday_sales
      get :current_week_sales
      get :last_week_sales
      get :current_month_sales
      get :last_month_sales
      get :room_status
    end
  end
end

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{get_flash_class(type)}") %>
<% end %>

app/views/shared/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header border-botton border-4 border-primary">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Close</button>
        <button type="button" class="btn btn-primary" id="modal-submit">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to 'Check-In Manager', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Rooms', rooms_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu">
            <%= link_to 'Room Categories', categories_path, class: "dropdown-item" %>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_hotel ? current_hotel.email : "User" %>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <%= link_to 'Sign Out', destroy_hotel_session_path, class: "dropdown-item", method: :delete %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_room_status.html.erb
<div class="container">
  <div class="row">
    <div class="col"><h3><strong>Available Rooms: </strong><%= @rooms[:available] %></h3></div>
    <div class="col"><h3><strong>Engaged Rooms: </strong><%= @rooms[:engaged] %></h3></div>
  </div>
</div>

app/views/shared/_toaster_flash.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s == 'alert' ? 'error' : 'success' %>
      toastr['<%= type %>']('<%= f[1] %>', {timeOut: 5000,closeButton: true,progressBar: true, positionClass: "toast-bottom-right"});
      <% end %>
  </script>
<% end %>

app/views/shared/_toastr_flash_new.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
    <% type = get_flash_type(f[0].to_s) %>
    $.toast({
      title:"<%= type.titleize %>",
      message:"<%= f[1] %>",
      type:"<%= type %>",
      duration: 5000,// auto-dismiss after 5s
    });
    <% end %>
  </script>
<% end %>

app/views/shared/_today_sales.html.erb
<div class="container">
  <div class="row">
    <div class="col">Amount:</div>
    <div class="col">36,512/-</div>
  </div>
</div>

app/views/shared/room_status.js.erb
$('.room_status').append('<%= escape_javascript(render partial: 'shared/room_status') %>');

app/views/shared/today_sales.js.erb
$('.today_sales').append('<%= escape_javascript(render partial: 'shared/today_sales') %>');