config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :rooms
  resources :categories
  devise_for :hotels
  resources :hotels
  resources :bookings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'home#index'
  resources :home, only: [:index] do
    collection do
      get :today_sales
      get :yesterday_sales
      get :current_week_sales
      get :last_week_sales
      get :current_month_sales
      get :last_month_sales
      get :room_status
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  enum status: { available: 'Available', checked_in: 'Checked In', not_clean: 'Not Clean', closed: 'Closed'}
  validates_presence_of :number
  belongs_to :category
  belongs_to :customer, optional: true
  has_many :room_bookings, dependent: :destroy
  has_many :bookings, through: :room_bookings
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    @room.status = 'Available'
    if @room.save
      redirect_to rooms_path, notice: "Room Created Successfully."
    end
  end

  def update
    if @room.update(room_params)
      redirect_to rooms_path, notice: "Room Updated Successfuly!"
    else
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:number, :category_id)
    end
end

app/views/rooms/_form.html.erb
<!-- _form.html.erb -->
<%= form_for(@room, remote: true, html: { class: "needs-validation" }) do |f| %>
  <% if @room.errors.any? %>
    <div class="alert alert-danger">
      <h6>Please fix these errors:</h6>
      <ul>
        <% @room.errors.full_messages.each do |message| %>
          <li><p><%= message %></p></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :number, class: "form-label" %>
    <%= f.number_field :number, class: "form-control", autofocus: true %>
  </div>

  <div class="mb-3">
    <%= f.label :category, class: "form-label" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, { prompt: "Select a category" }, { class: "form-control" }) %>
  </div>

  <div class="modal-footer">
    <%= f.submit nil, class: "submit-form d-none" %>
  </div>
<% end %>

app/views/rooms/_show.html.erb
<h1><%= @room.number %></h1>

app/views/rooms/create.js.erb
<% if @room.errors.any? %>
  $('.modal-body').html('<%= escape_javascript(render "form") %>');
<% else %>
  window.location.reload();
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/edit.js.erb
$('.modal-title').html('Edit Room');
$('.modal-body').html('<%= escape_javascript(render "form") %>');
$('#exampleModalCenter').modal('show');

app/views/rooms/index.html.erb
<div class="d-flex justify-content-between ms-0 m-4">
  <div class="float-left">
    <h1>Rooms</h1>
  </div>
  <div class="float-right">
    <%= link_to "New Room", new_room_path, class: "btn btn-primary float-right", remote: true %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col" >Number</th>
      <th scope="col">Category</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <div id="categories">
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.number %></td>
          <td><%= room.category.name %></td>
          <td><%= Room.statuses[room.status] %></td>
          <td>
            <%= link_to "Show", room_path(room), class: 'badge btn btn-primary btn-sm', remote: true %>
            <%= link_to "Edit", edit_room_path(room), class: 'badge btn btn-dark btn-sm', remote: true %>
            <%= link_to "Delete", room_path(room), data: {confirm: 'Are you sure?'}, method: :delete, class: 'badge btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </div>
  </tbody>
</table>

app/views/rooms/new.js.erb
$('.modal-title').html('New Room');
$('.modal-body').html('<%= escape_javascript(render "form") %>');
$('#exampleModalCenter').modal('show');

app/views/rooms/show.js.erb
$('.modal-title').html('Room Details');
$('.modal-body').html('<%= escape_javascript(render "show") %>');
$('#exampleModalCenter').modal('show');