config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :rooms
  resources :categories
  devise_for :hotels
  resources :hotels
  resources :bookings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'home#index'
  resources :home, only: [:index] do
    collection do
      get :today_sales
      get :yesterday_sales
      get :current_week_sales
      get :last_week_sales
      get :current_month_sales
      get :last_month_sales
      get :room_status
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    result = CreateRecord.call(@category)
    if result[:success]
      redirect_to categories_path, notice: 'Category Successfully Created'
    else
      @category = result[:object]
    end
  end

  def update
    result = UpdateRecord.call(@category, category_params)
    if result[:success]
      redirect_to categories_path, notice: 'Category Successfully Updated'
    else
      binding.pry 
      @category = result[:object]
    end
  end

  def destroy
    @category.destroy!
    redirect_to categories_url, alert: "Category was successfully destroyed."
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/views/categories/_form.html.erb
<%= form_for(@category, remote: true, html: { class: "needs-validation" }) do |f| %>
  <% if @category.errors.any? %>
    <div class="alert alert-danger">
      <h6>Please fix these errors:</h6>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><p><%= message %></p></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control", autofocus: true %>
  </div>

  <div class="modal-footer">
    <%= f.submit nil, class: "submit-form d-none" %>
  </div>
<% end %>

app/views/categories/create.js.erb
<% if @category.errors.any? %>
  $('.modal-body').html('<%= escape_javascript(render "form") %>');
<% end %>
  

app/views/categories/edit.js.erb
$('.modal-title').html('Edit Room Category');
$('.modal-body').html('<%= escape_javascript(render "form") %>');
$('#exampleModalCenter').modal('show');
$('#modal-submit').text('Update');

app/views/categories/index.html.erb
<div class="d-flex justify-content-between ms-0 m-4">
  <div class="float-left">
    <h1>Room Categories</h1>
  </div>
  <div class="float-right">
    <%= link_to "New Category", new_category_path, class: "btn btn-primary float-right", remote: true %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <div id="categories">
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td>
            <%= link_to "Edit", edit_category_path(category), class: 'btn btn-outline-dark btn-sm', remote: true %>
            <%= link_to "Delete", category_path(category), data: {confirm: 'Are you sure?'}, method: :delete, class: 'btn btn-outline-danger btn-sm' %></td>
        </tr>
      <% end %>
    </div>
  </tbody>
</table>

app/views/categories/new.js.erb
$('.modal-title').html('New Room Category');
$('.modal-body').html('<%= escape_javascript(render "form") %>');
$('#exampleModalCenter').modal('show');
$('#modal-submit').text('Save');

app/views/categories/update.js.erb
<% if @category.errors.any? %>
  $('.modal-body').html('<%= escape_javascript(render "form") %>');
<% end %>