config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :rooms
  resources :categories
  devise_for :hotels
  resources :hotels
  resources :bookings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root 'home#index'
  resources :home, only: [:index] do
    collection do
      get :today_sales
      get :yesterday_sales
      get :current_week_sales
      get :last_week_sales
      get :current_month_sales
      get :last_month_sales
      get :room_status
    end
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy!

    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :owner_name, :mobile_number, :gst, :address, :city, :state)
    end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel) do |form| %>
  <% if hotel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% hotel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :owner_name, style: "display: block" %>
    <%= form.text_field :owner_name %>
  </div>

  <div>
    <%= form.label :mobile_number, style: "display: block" %>
    <%= form.number_field :mobile_number %>
  </div>

  <div>
    <%= form.label :gst, style: "display: block" %>
    <%= form.text_field :gst %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/_hotel.html.erb
<div id="<%= dom_id hotel %>">
  <p>
    <strong>Name:</strong>
    <%= hotel.name %>
  </p>

  <p>
    <strong>Owner name:</strong>
    <%= hotel.owner_name %>
  </p>

  <p>
    <strong>Mobile number:</strong>
    <%= hotel.mobile_number %>
  </p>

  <p>
    <strong>Gst:</strong>
    <%= hotel.gst %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= hotel.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= hotel.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= hotel.state %>
  </p>

</div>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Show this hotel", @hotel %> |
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Hotels</h1>

<div id="hotels">
  <% @hotels.each do |hotel| %>
    <%= render hotel %>
    <p>
      <%= link_to "Show this hotel", hotel %>
    </p>
  <% end %>
</div>

<%= link_to "New hotel", new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render "form", hotel: @hotel %>

<br>

<div>
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hotel %>

<div>
  <%= link_to "Edit this hotel", edit_hotel_path(@hotel) %> |
  <%= link_to "Back to hotels", hotels_path %>

  <%= button_to "Destroy this hotel", @hotel, method: :delete %>
</div>